#include <stdio.h>
/* ifstmt
 Parses strings in the language generated by the rule:
 <ifstmt> -> if "(" <logic_expr> ")" "{" <statement> "}"
 [else <statement>]
 */

void if_stmt(void) {
    if (nextToken != IF_CODE) {
        error();
    }
    else {
        lex();
        if (nextToken != LEFT_PAREN) {
            error();
        }
        else {
            lex();
            logic_expr();
            while (nextToken != RIGHT_PAREN) {
                logic_expr();
            }
            if (nextToken != RIGHT_PAREN) {
                error();
            }
            else {
                lex();
                if (nextToken != LEFT_CURLY) {
                    error();
                }
                else {
                    lex();
                    if (nextToken != RIGHT_CURLY) {
                        statement();
                    }
                    if (nextToken != RIGHT_CURLY) {
                        error();
                    }
                }
            }
        }
    }
}

