#include <stdio.h>
/* While Statement
Parses strings in the language generated by the rule :
<whilestmt> -> while "(" <logic_expr> ")" "{" <statement> "}"
[do <statement>]
*/ 

void body_block();

void while_stmt(void) {
    if (nextToken != WHILE_CODE) {
        error();
    }
    else {
        lex();
        if (nextToken != LEFT_PAREN) {
            error();
        }
        else {
            lex();
            logic_expr();
            while (nextToken != LEFT_PAREN) {
                logic_expr();
            }
            if (nextToken != RIGHT_PAREN) {
                error();
            }
            else {
                lex();
                if (nextToken != LEFT_CURLY) {
                    error();
                }
                else {
                    lex();
                    while (nextToken != RIGHT_CURLY) {
                        statement();
                    }
                    if (nextToken != RIGHT_CURLY) {
                        error();
                    }
                }
            }
        }
    }
}
